import cmor
import xcdat as xc
import xarray as xr  # xcdat depends on xarray; imported for type compatibility
import numpy as np
import urllib.request
import tempfile
import json
import sys
import os

sys.path.append("../../../misc")  # Path to obs4MIPsLib used to trap provenance
import obs4MIPsLib

cmorTable     = '../../../../Tables/obs4MIPs_Amon.json'  # Load target table, axis info (coordinates, grid*) and CVs
inputJson     = 'HadCRUT5.1.0.0.json'                    # Update contents of this file to set global_attributes
inputVarName  = 'tas_mean'                               # Variable name in the HadCRUT5 ensemble mean NetCDF
outputVarName = 'tastosanom-MOHC'                        # Variable name as defined in obs4MIPs_Amon.json
outputUnits   = '1'                                      # TODO: CMOR table obs4MIPs_Amon.json defines tastosanom-MOHC with units="1" (dimensionless).
                                                         # This should be "K" for temperature anomalies - raise with PCMDI to fix in master branch.
                                                         # Using "1" here to match the table as-is so the script runs locally.

# Missing-data indicator used by CMOR and applied to fill NaN values before write.
# Must match the missing_value passed to cmor.variable() below.
CMOR_MDI = 1.e20

# ── Download input data ────────────────────────────────────────────────────────
# The Met Office HadObs server does not support OPeNDAP, so the file is always
# downloaded fresh from the official source URL into a temporary directory.
# This avoids any dependency on local file paths and ensures reproducibility for
# all users. The temporary directory is removed automatically when the script ends.
# sourceURL is also referenced in test_HadCRUT5.1.0.0.py — update both if the URL changes.
sourceURL = 'https://www.metoffice.gov.uk/hadobs/hadcrut5/data/HadCRUT.5.1.0.0/analysis/HadCRUT.5.1.0.0.analysis.anomalies.ensemble_mean.nc'
print(f"\n[1/6] Downloading input data")
print(f"      Source : {sourceURL}")
_tmpdir = tempfile.TemporaryDirectory()
try:
    inputFilePath = os.path.join(_tmpdir.name, os.path.basename(sourceURL))
    urllib.request.urlretrieve(sourceURL, inputFilePath)
    print(f"      Saved to temporary directory: {_tmpdir.name}")

    # ── Open and read input netcdf file, prepare coordinates and bounds ────────────
    print(f"\n[2/6] Reading input file and preparing coordinates")
    f = xc.open_dataset(inputFilePath, decode_times=False)

    # ── Capture source state before any xcdat modifications ───────────────────
    _src_dtype      = f[inputVarName].dtype
    _src_units_attr = f[inputVarName].attrs.get('units', '(not set)')
    _lat_pre        = f.latitude.values
    _lon_pre        = f.longitude.values
    _lat_ascending  = bool(_lat_pre[0] < _lat_pre[-1])
    _lon_convention = "0\u2192360" if _lon_pre.min() >= 0 else "-180\u2192180"
    # Check which bounds exist in the source before xcdat touches anything
    _has = lambda n: n in f or n in f.coords
    _lat_bnds_before  = _has('latitude_bnds')  or _has('lat_bnds')
    _lon_bnds_before  = _has('longitude_bnds') or _has('lon_bnds')
    _time_bnds_before = _has('time_bnds')      or _has('time_bounds')
    _tbds_orig        = f['time_bnds'].values.copy() if _time_bnds_before else None

    # ── Add missing spatial bounds (xcdat skips axes that already have bounds) ─
    f = f.bounds.add_missing_bounds(axes=['X', 'Y'])

    # ── Add/regenerate time bounds (add_bounds always rewrites the variable) ───
    f = f.bounds.add_bounds("T")
    _time_bnds_changed = (_tbds_orig is None) or not np.allclose(_tbds_orig, f.time_bnds.values)

    d    = f[inputVarName]             # Assign AFTER bounds are added so f is fully prepared
    lat  = f.latitude.values
    lon  = f.longitude.values
    time = f.time.values
    tbds = f.time_bnds.values

    print(f"      Variable  : {inputVarName}  {d.shape}  (source dtype: {_src_dtype})")
    print(f"      Time range: {time[0]:.1f} to {time[-1]:.1f} ({f.time.attrs.get('units', '')})")
    print(f"      Grid      : {len(lat)} lats x {len(lon)} lons")
    _lat_flip = "no CMOR flip needed" if _lat_ascending else "CMOR WILL FLIP to S\u2192N"
    print(f"      Latitude  : {_lat_pre[0]:.1f}\u00b0 to {_lat_pre[-1]:.1f}\u00b0  "
          f"({'ascending S\u2192N' if _lat_ascending else 'descending N\u2192S'})  \u2014  {_lat_flip}")
    _lon_warn = ("  \u2190 NOTE: obs4MIPs typically uses 0\u2192360; verify downstream compatibility"
                 if _lon_convention == "-180\u2192180" else "")
    print(f"      Longitude : {_lon_pre[0]:.1f}\u00b0 to {_lon_pre[-1]:.1f}\u00b0  [{_lon_convention}]{_lon_warn}")

    def _bnds_msg(had_before):
        return "already in source \u2014 xcdat left unchanged" if had_before else "absent in source \u2014 generated by xcdat (\u00b1half cell-width)"
    print(f"      Lat bnds  : {_bnds_msg(_lat_bnds_before)}")
    print(f"      Lon bnds  : {_bnds_msg(_lon_bnds_before)}")
    if _time_bnds_before:
        _tbds_note = "values changed" if _time_bnds_changed else "values unchanged"
        print(f"      Time bnds : already in source \u2014 xcdat regenerated ({_tbds_note})")
    else:
        print(f"      Time bnds : absent in source \u2014 generated by xcdat (\u00b1half mean step)")

    # ── Count NaNs and measure float32 precision impact before replacement ─────
    _src_finite   = d.values[np.isfinite(d.values)]
    _nan_count    = int(d.size - len(_src_finite))
    _max_f32_err  = (float(np.abs(_src_finite.astype(np.float64) -
                                   _src_finite.astype(np.float32).astype(np.float64)).max())
                     if len(_src_finite) else 0.0)

    # Replace NaNs with CMOR missing value before conversion to float32
    d = np.where(np.isnan(d), CMOR_MDI, d)
    print(f"      NaN\u21921e20  : {_nan_count:,} missing values replaced "
          f"({100*_nan_count/d.size:.1f}% of all grid points)")

    # ── Read output settings from JSON to show user where output will be written ───
    with open(inputJson) as _fh:
        _cfg = json.load(_fh)
    _outpath  = _cfg.get('outpath', './')
    _path_tpl = _cfg.get('output_path_template', '')
    _file_tpl = _cfg.get('output_file_template', '')
    print(f"\n[3/6] Initialising CMOR")
    print(f"      Config    : {inputJson}")
    print(f"      CV/Tables : {cmorTable}")
    print(f"      Output will be written under: {os.path.abspath(_outpath)}")
    print(f"      Path template : {_path_tpl}")
    print(f"      File template : {_file_tpl}")

    # Initialize and run CMOR. For more information see https://cmor.llnl.gov/mydoc_cmor3_api/
    # CMOR_REPLACE_4: any existing output file with the same name will be silently overwritten.
    cmor.setup(inpath='./', netcdf_file_action=cmor.CMOR_REPLACE_4)  # ,logfile='cmorLog.txt'
    cmor.dataset_json(inputJson)
    cmor.load_table(cmorTable)
    cmor.set_cur_dataset_attribute('history', f.attrs.get('history', ''))
    # Read table out_name so step [5/6] can report the actual output variable name
    with open(cmorTable) as _ft:
        _tbl_out_name = (json.load(_ft)
                         .get('variable_entry', {})
                         .get(outputVarName, {})
                         .get('out_name', outputVarName))

    # ── Create CMOR axes ───────────────────────────────────────────────────────────
    print(f"\n[4/6] Creating CMOR axes")
    cmorLat  = cmor.axis("latitude",  coord_vals=lat[:],  cell_bounds=f.latitude_bnds.values,  units="degrees_north")
    cmorLon  = cmor.axis("longitude", coord_vals=lon[:],  cell_bounds=f.longitude_bnds.values,  units="degrees_east")
    cmorTime = cmor.axis("time",      coord_vals=time[:], cell_bounds=tbds,                     units=f.time.units)
    cmoraxes = [cmorTime, cmorLat, cmorLon]
    print(f"      latitude ({len(lat)}), longitude ({len(lon)}), time ({len(time)})")

    # ── Create CMOR variable ───────────────────────────────────────────────────────
    print(f"\n[5/6] Writing CMORised output")
    print(f"      CMOR will apply the following changes (not yet written):")
    print(f"        variable name  : '{inputVarName}'  will be renamed to  '{_tbl_out_name}'  (table out_name)")
    _units_issue = "  \u2190 KNOWN TABLE ISSUE: should be 'K'; raise with PCMDI" if outputUnits == '1' else ""
    print(f"        units          : '{_src_units_attr}' (source)  will be set to  '{outputUnits}' (table){_units_issue}")
    print(f"        dtype          : {_src_dtype}  will be cast to  float32  (pre-measured max loss: {_max_f32_err:.2e} {_src_units_attr})")
    print(f"        long_name      : will be overridden to include the 1961-1990 climatological reference period")
    print(f"        units_metadata : will be set to 'temperature: difference'")
    varid  = cmor.variable(outputVarName, outputUnits, cmoraxes, missing_value=CMOR_MDI)
    values = np.array(d, np.float32)

    # Set bespoke long_name to include climatology period
    cmor.set_variable_attribute(varid, 'long_name', 'c',
        'Near-surface land and ocean temperature monthly mean anomalies from the 1961-1990 climatological reference period')
    cmor.set_variable_attribute(varid, 'units_metadata', 'c', 'temperature: difference')

    # Provenance info - produces global attribute <processing_code_location>
    git_commit_number = obs4MIPsLib.get_git_revision_hash()
    path_to_code = os.getcwd().split('obs4MIPs-cmor-tables')[1].lstrip('/')
    full_git_path = f"https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/{git_commit_number}/{path_to_code}"
    cmor.set_cur_dataset_attribute("processing_code_location", f"{full_git_path}")

    # Compress and write - see https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_set_variable_attribute
    cmor.set_deflate(varid, 1, 1, 1)  # shuffle=1, deflate=1, deflate_level=1
    cmor.write(varid, values, len(time))

    # Close the variable file and capture the output path for reporting.
    # cmor.close(varid, file_name=True) finalises and closes the file in one call -
    # a second bare cmor.close() is not needed and can leave NFS lock files behind.
    outfile = cmor.close(varid, file_name=True)
    f.close()

    print(f"      Done. Output file written to:")
    print(f"      {os.path.abspath(outfile)}")

finally:
    # ── Cleanup ────────────────────────────────────────────────────────────────────
    print(f"\n[6/6] Cleaning up temporary download directory")
    _tmpdir.cleanup()
    print(f"      Complete.\n")
