source_id = {}
source_id['source_id'] = {}

key = 'PRISM-M3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'PRISM'
source_id['source_id'][key]['source_label'] = 'PRISM'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_description'] = 'PRISM Spatial Climate Datasets for CONUS'
source_id['source_id'][key]['source_version_number'] = 'M3'
source_id['source_id'][key]['institution_id'] = 'OSU'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','tas']

key = 'livneh-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'livneh'
source_id['source_id'][key]['source_label'] = 'livneh'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS near-surface gridded meteorological and derived hydrometeorological data data provided by the NOAA PSL'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-ESRL-PSD'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','sfcWind']

key = 'livneh-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'livneh'
source_id['source_id'][key]['source_label'] = 'livneh'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS near-surface gridded meteorological and derived hydrometeorological data data provided by the NOAA PSL'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-ESRL-PSD'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','sfcWind']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'livneh-unsplit-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'livneh_unsplit' 
source_id['source_id'][key]['source_label'] = 'livneh_unsplit'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS unsplit'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'UCSD-SIO'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','sfcWind'] 

key = 'GERB-HR-ED01-1-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'GERB'
source_id['source_id'][key]['source_label'] = 'GERB'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_description'] = 'Geostationary Earth Radiation Budget'
source_id['source_id'][key]['institution_id'] = 'ImperialCollege'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['source_variables'] = ['rlut','rsut']
source_id['source_id'][key]['source_version_number'] = 'HR_ED01_1.1'

key = 'MSWEP-V280-Past'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MSWEP'
source_id['source_id'][key]['source_label'] = 'MSWEP'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Multi-Source Weighted-Ensemble Precipitation'
source_id['source_id'][key]['institution_id'] = 'GloH2O'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V280-Past'

key = 'MSWEP-V280-Past-nogauge'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MSWEP'
source_id['source_id'][key]['source_label'] = 'MSWEP'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Multi-Source Weighted-Ensemble Precipitation'
source_id['source_id'][key]['institution_id'] = 'GloH2O'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V280-Past-nogauge'

key = 'MSWEP-V280-NRT'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MSWEP'
source_id['source_id'][key]['source_label'] = 'MSWEP'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Multi-Source Weighted-Ensemble Precipitation'
source_id['source_id'][key]['institution_id'] = 'GloH2O'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V280-Past-NRT'

key = 'MUR25-4-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MUR25'
source_id['source_id'][key]['source_label'] = 'MUR25'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_description'] = 'Multiscale Ultrahigh Resolution L4 Sea-Surface Temperature'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['source_variables'] = ['tos']
source_id['source_id'][key]['source_version_number'] = 'v4.2'

key = 'IMERG-V06-EU'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS near-surface gridded meteorological and derived hydrometeorological data'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-EU'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-EU'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-EU'

key = 'IMERG-V06-FC'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-FC'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-FC'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-FC'

key = 'IMERG-V06B-Final-3hr'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG averaged to 3-hourly maps'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-Final-3hr'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-Final-3hr'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06B'

key = 'IMERG-V07-Final'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG 30-min, 0.1x0.1 degrees'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V07-Final'
source_id['source_id'][key]['source_name'] = 'IMERG-V07-Final'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V07'

key = 'IMERG-V06-FU'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-FU'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-FU'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-FU'

key = 'IMERG-V06-LU'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-LU'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-LU'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-LU'

key = 'nClimGrid-Monthly-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'nClimGrid-Monthly-1-0'
source_id['source_id'][key]['release_year'] = '2014'
source_id['source_id'][key]['source_description'] = 'NOAA nClimGrid-Monthly'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = 'north_america'
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'nClimGrid-Monthly-1-0'
source_id['source_id'][key]['source_variables'] = ['pr','tas','tasmax','tasmin']

key = 'nClimGrid-Daily-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'nClimGrid-Daily-1-0'
source_id['source_id'][key]['release_year'] = '2014'
source_id['source_id'][key]['source_description'] = 'NOAA nClimGrid-Daily'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = 'north_america'
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'nClimGrid-Daily-1-0'
source_id['source_id'][key]['source_variables'] = ['pr','tas','tasmax','tasmin']

key = 'OISST-L4-AVHRR-only-v2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'SST-AVHRR_only.v2 2008 NOAA 1/4 Degree Daily Optimum Interpolation Sea Surface Temperature Analysis using AVHRR, Version 2'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'OISST_L4_AVHRR-only-v2'
source_id['source_id'][key]['source_name'] = 'OISST_L4_AVHRR-only-v2'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_variables'] = ['ts']
source_id['source_id'][key]['source_version_number'] = 'v2'

key = 'HadISST-1-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'HadISST 1.1 monthly average sea surface temperature'
source_id['source_id'][key]['institution_id'] = 'MOHC'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'HadISST-1-1'
source_id['source_id'][key]['source_name'] = 'HadISST-1-1'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_variables'] = ['ts']
source_id['source_id'][key]['source_version_number'] = '1-1'

key = 'AVISO-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Gridded sea surface heights above geoid'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'AVISO-1-0'
source_id['source_id'][key]['source_name'] = 'AVISO-1-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['zos']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'TropFlux-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'TropFlux - Air-Sea Fluxes for the Global Tropical Oceans'
source_id['source_id'][key]['institution_id'] = 'INCOIS-NIO-IPSL'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TropFlux-1-0'
source_id['source_id'][key]['source_name'] = 'TropFlux-1-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_variables'] = ['tas','ts','hfls','hfss','hfns','tauu','tauv']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'AVISO-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Gridded sea surface heights above geoid'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'AVISO-1-0'
source_id['source_id'][key]['source_name'] = 'AVISO-1-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['zos']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'CERES-EBAF-4-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages'
source_id['source_id'][key]['institution_id'] = 'NASA-LaRC'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CERES-EBAF-4-0'
source_id['source_id'][key]['source_name'] = 'CERES-EBAF4-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['rlut','rsut','rsutcs','rlutcs']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'CERES-EBAF-4-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages'
source_id['source_id'][key]['institution_id'] = 'NASA-LaRC'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CERES-EBAF'
source_id['source_id'][key]['source_name'] = 'CERES-EBAF'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['rlut','rsut','rsutcs','rlutcs']
source_id['source_id'][key]['source_version_number'] = '4.1'

key = 'CERES-EBAF-4-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages'
source_id['source_id'][key]['institution_id'] = 'NASA-LaRC'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CERES-EBAF-4-2'
source_id['source_id'][key]['source_name'] = 'CERES-EBAF4-2'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['rlut','rsut','rsutcs','rlutcs']
source_id['source_id'][key]['source_version_number'] = '4.2'

key = 'ERA-40'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF - ERA-40 (European ReAnalysis 1957-2002)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2005'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERA-40'
source_id['source_id'][key]['source_name'] = 'ECMWF ERA-40'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'ERA-5'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ERA5 (European ReAnalysis)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERA-5'
source_id['source_id'][key]['source_name'] = 'ECMWF ERA-5'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tas','psl','zg','ta','ua','va','pr']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'CMAP-V1902'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CMAP Precipitation'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CMAP'
source_id['source_id'][key]['source_name'] = 'CMAP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V1902'

key = 'CMORPH-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CMORPH'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CMORPH'
source_id['source_id'][key]['source_name'] = 'CMORPH'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'CMORPH-1-0-CRT'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NOAA CMORPH prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CMORPH'
source_id['source_id'][key]['source_name'] = 'CMORPH'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'GPCP-2-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '2.3'

key = 'GPCP-1-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.3'

key = 'GPCP-1DD-CDR-v1-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Daily GPCP CDR prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.3'

key = 'GPCP-IP'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA GPCP prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.3'

key = 'GSMAP-gauges-NRT-v6-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'JAXA GSMAP prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'JAXA'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GSMAP'
source_id['source_id'][key]['source_name'] = 'GSMAP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '6.0'

key = 'ERA-INT'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF-ERAINT 1.0 (2010): ECMWF - ERAINT (European ReAnalysis 1989-2010)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2010'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERAINT'
source_id['source_id'][key]['source_name'] = 'ECMWF-ERAINT'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va','zg']
source_id['source_id'][key]['source_version_number'] = 'N/A'

key = 'JRA25'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'JRA25 1.0 (2002): JRA25 (Japanese ReAnalysis 1957-2002)'
source_id['source_id'][key]['institution_id'] = 'MRI'
source_id['source_id'][key]['release_year'] = '2002'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'MRI-JRA25'
source_id['source_id'][key]['source_name'] = 'MRI-JRA25'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va','zg']
source_id['source_id'][key]['source_version_number'] = 'N/A'

key = '20CR-V2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Monthly NOAA-CIRES 20th Century Reanalysis V2'
source_id['source_id'][key]['institution_id'] = 'NOAA-ESRL-PSD'
source_id['source_id'][key]['release_year'] = '2006'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = '20CR'
source_id['source_id'][key]['source_name'] = '20CR'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ts','psl']
source_id['source_id'][key]['source_version_number'] = 'V2'

key = 'ERA-20C'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF - ERA-20C (European ReAnalysis 1900-2010)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2014'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERA-20C'
source_id['source_id'][key]['source_name'] = 'ECMWF ERA-20C'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ts','psl']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'TRMM-3B42v-7'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA-TRMM prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TRMM'
source_id['source_id'][key]['source_name'] = 'TRMM'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3B42v.7'

key = 'TRMM-3B42-IR-v7-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA-TRMM prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TRMM'
source_id['source_id'][key]['source_name'] = 'TRMM'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3B42.IR.v7.0'

key = 'TRMM-3B42-MW-v7-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA-TRMM prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TRMM'
source_id['source_id'][key]['source_name'] = 'TRMM'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3B42.MW.v7.0'

key = 'RSS-MSU-TLS-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MSU Temperature Lower Stratosphere v4.0'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MSU-TLS'
source_id['source_id'][key]['source_name'] = 'RSS-MSU-TLS'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tls']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'RSS-MSU-TLT-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MSU Temperature Lower Troposphere v4.0'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MSU-TLT'
source_id['source_id'][key]['source_name'] = 'RSS-MSU-TLT'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tlt']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'RSS-MSU-TMT-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MSU Temperature Middle Troposphere v4.0'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MSU-TMT'
source_id['source_id'][key]['source_name'] = 'RSS-MSU-TMT'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tmt']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'RSS-MWIR-SST-5-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MWIR v5.1 Foundation OISST'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MWIR-SST'
source_id['source_id'][key]['source_name'] = 'RSS-MWIR-SST'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tos']
source_id['source_id'][key]['source_version_number'] = '5.1'

key = 'RSS-PRW-6-6-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-PRW 6.6.0 (2017): Water Vapor Path'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-PRW'
source_id['source_id'][key]['source_name'] = 'RSS-PRW'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['prw']
source_id['source_id'][key]['source_version_number'] = '6.6.0'

key = 'RSS-PRW-v07r01'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-PRW 7.0 (2019): Water Vapor Path'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-PRW'
source_id['source_id'][key]['source_name'] = 'RSS-PRW'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['prw']
source_id['source_id'][key]['source_version_number'] = '7.1'

key = 'RSS-PRW-v07r02'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-PRW 7.2 (2022): Water Vapor Path'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-PRW'
source_id['source_id'][key]['source_name'] = 'RSS-PRW'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['prw']
source_id['source_id'][key]['source_version_number'] = '7.2'

key = 'RSS-SMAP-SSS-v05r01'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Satellite derived SSS produced by RSS'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-SMAP-SSS'
source_id['source_id'][key]['source_name'] = 'RSS-SMAP-SSS'
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['region'] = ['global ocean']
source_id['source_id'][key]['source_variables'] = ['sos']
source_id['source_id'][key]['source_version_number'] = '5.0'

key = 'RSS-sfcWind-v07r01'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-sfcWind 7.0 (2021): 10m Surface Wind'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-sfcWind'
source_id['source_id'][key]['source_name'] = 'RSS-sfcWind'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['sfcWind']
source_id['source_id'][key]['source_version_number'] = '7.1'

key = 'PERSIANN-CDRv1r1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NOAA PERSIANN prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = '2015'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'PERSIANN'
source_id['source_id'][key]['source_name'] = 'PERSIANN'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'CDRv1r1'

key = 'C3S-GTO-ECV-9-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'C3S-GTO-ECV'
source_id['source_id'][key]['source_label'] = 'C3S-GTO-ECV'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_description'] = 'GOME-type Total Ozone Essential Climate Variable (GTO-ECV), generated by combining measurements from several nadir-viewing satellite sensors (GOME/ERS-2, SCIAMACHY/Envisat, OMI/Aura, GOME-2/MetOp-A, GOME-2/MetOp-B, GOME-2/MetOp-C, and TROPOMI/Sentinel-5p'
source_id['source_id'][key]['source_version_number'] = '9.0'
source_id['source_id'][key]['institution_id'] = 'DLR-BIRA'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['o3']
source_id['source_id'][key]['source_id'] = key

