source_id = {}
source_id['source_id'] = {}

key = 'AI-upscaling-0-30cm-cSoil-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'AI upscaling 0-30 cm cSoil'
source_id['source_id'][key]['source_label'] = 'AI-upscaling-0-30cm-cSoil'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Upscaled 0-30 cm soil organic carbon stock for the United States using multivariate geographic clustering and machine learning'
source_id['source_id'][key]['source_version_number'] = '1'
source_id['source_id'][key]['institution_id'] = 'EmoryU'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'AI_upscaling'
source_id['source_id'][key]['source_variables'] = ['cSoil0to30cm']

key = 'AI-upscaling-0-100cm-cSoil-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'AI upscaling 0-100 cm cSoil'
source_id['source_id'][key]['source_label'] = 'AI-upscaling-0-100cm-cSoil'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Upscaled 0-100 cm soil organic carbon stock for the United States using multivariate geographic clustering and machine learning'
source_id['source_id'][key]['source_version_number'] = '1'
source_id['source_id'][key]['institution_id'] = 'EmoryU'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'AI_upscaling'
source_id['source_id'][key]['source_variables'] = ['cSoil0to100cm']

key = 'ESACCI-SCFG-MODIS-v4-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ESACCI-SCFG-MODIS'
source_id['source_id'][key]['source_label'] = 'ESACCI-SCFG-MODIS'
source_id['source_id'][key]['release_year'] = '2025'
source_id['source_id'][key]['source_description'] = 'Snow Cover Fraction on Ground (SCFG) derived from Terra MODIS data from the ESA SNOW CCI Climate Data Record version 4.0'
source_id['source_id'][key]['source_version_number'] = 'v4.0'
source_id['source_id'][key]['institution_id'] = 'ENVEO'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['sncfg', 'sncfv', 'sncfgstderr','sncfvstderr', 'snc']

key = 'ESACCI-SCFV-MODIS-v4-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ESACCI-SCFV-MODIS'
source_id['source_id'][key]['source_label'] = 'ESACCI-SCFV-MODIS'
source_id['source_id'][key]['release_year'] = '2025'
source_id['source_id'][key]['source_description'] = 'Snow Cover Fraction Viewable from above (SCFV) derived from Terra MODIS data from the ESA SNOW CCI Climate Data Record version 4.0'
source_id['source_id'][key]['source_version_number'] = 'v4.0'
source_id['source_id'][key]['institution_id'] = 'ENVEO'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['sncfg', 'sncfv', 'sncfgstderr','sncfvstderr', 'snc']

key = 'ESACCI-LST-IRMGP-3-0-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ESACCI-LST-IRMGP'
source_id['source_id'][key]['source_label'] = 'ESACCI-LST-IRMGP'
source_id['source_id'][key]['release_year'] = '2026'
source_id['source_id'][key]['source_description'] = 'ESA Land Surface Temperature Climate Change Initiative Multisensor Infra-Red Low Earth Orbit and Geostationary Earth Orbit land surface temperature'
source_id['source_id'][key]['source_version_number'] = '3.00'
source_id['source_id'][key]['institution_id'] = 'ULeicester'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['source_variables'] = ['ts', 'tsuind', 'tsustr', 'tsucom']

key = 'ESACCI-LST-AMSR-6-0-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ESACCI-LST-AMSR'
source_id['source_id'][key]['source_label'] = 'ESACCI-LST-AMSR'
source_id['source_id'][key]['release_year'] = '2026'
source_id['source_id'][key]['source_description'] = 'ESA Land Surface Temperature Climate Change Initiative AMSR-E and AMSR2 Microwave Low Earth Orbit land surface temperature'
source_id['source_id'][key]['source_version_number'] = '6.04'
source_id['source_id'][key]['institution_id'] = 'Estellus'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['ts', 'tsuind']

key = 'ESACCI-LST-SSMI-6-0-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ESACCI-LST-SSMI'
source_id['source_id'][key]['source_label'] = 'ESACCI-LST-SSMI'
source_id['source_id'][key]['release_year'] = '2026'
source_id['source_id'][key]['source_description'] = 'ESA Land Surface Temperature Climate Change Initiative SSM/I and SSMIS Microwave Low Earth Orbit land surface temperature'
source_id['source_id'][key]['source_version_number'] = '6.04'
source_id['source_id'][key]['institution_id'] = 'Estellus'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['ts', 'tsuind']

key = '20CR-V3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = '20CR'
source_id['source_id'][key]['source_label'] = '20CR'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_description'] = 'Monthly NOAA/CIRES/DOE 20th Century Reanalysis V3'
source_id['source_id'][key]['source_version_number'] = 'V3'
source_id['source_id'][key]['institution_id'] = 'NOAA-ESRL-PSD'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['source_variables'] = ['psl','tas']

key = 'HadCRUT5-0-2-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'HadCRUT5'
source_id['source_id'][key]['source_label'] = 'HadCRUT5'
source_id['source_id'][key]['release_year'] = '2025'
source_id['source_id'][key]['source_description'] = 'HadCRUT5 blended air temperature and sea surface temperature anomalies'
source_id['source_id'][key]['source_version_number'] = '5.0.2.0'
source_id['source_id'][key]['institution_id'] = 'CRU-UEA'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['tastosanom']

key = 'HadCRUT-5-1-0-0-analysis'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'HadCRUT5'
source_id['source_id'][key]['source_label'] = 'HadCRUT5'
source_id['source_id'][key]['release_year'] = '2025'
source_id['source_id'][key]['source_description'] = 'HadCRUT5 blended air temperature and sea surface temperature anomalies'
source_id['source_id'][key]['source_version_number'] = '5.1.0.0'
source_id['source_id'][key]['institution_id'] = 'CRU-UEA'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['tastosanom']
