source_id = {}
source_id['source_id'] = {}

key = 'wang2024-cSoil-v2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'wang2024 cSoil'
source_id['source_id'][key]['source_label'] = 'wang2024-cSoil'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Upscaling soil organic carbon measurements at the continental scale using multivariate clustering analysis and machine learning'
source_id['source_id'][key]['source_version_number'] = '2'
source_id['source_id'][key]['institution_id'] = 'EmoryU'
source_id['source_id'][key]['region'] = ['contiguous_united_states']
source_id['source_id'][key]['source_type'] = 'AI_upscaling'
source_id['source_id'][key]['source_variables'] = ['cSoil']

key = 'NOAA-NCEI-LAI-VIIRS-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'NOAA NCEI LAI v1.0 (2023): VIIRS Leaf Area Index'
source_id['source_id'][key]['source_label'] = 'NOAA-NCEI-LAI-VIIRS'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_description'] = 'Monthly Average of Daily Leaf Area Index from VIIRS'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['lai']

key = 'NOAA-NCEI-LAI-AVHRR-5-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'NOAA NCEI LAI v5.0 (2019): AVHRR Leaf Area Index'
source_id['source_id'][key]['source_label'] = 'NOAA-NCEI-LAI-AVHRR'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_description'] = 'Monthly Average of Daily Leaf Area Index from AVHRR'
source_id['source_id'][key]['source_version_number'] = '5.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['lai']


key = 'MGOHCTA-WOA09'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MGOHCTA'
source_id['source_id'][key]['source_label'] = 'MGOHCTA'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Monthly Global Ocean Heat Content and Temperature Anomalies in-situ (basin averages)'
source_id['source_id'][key]['source_version_number'] = 'WOA09'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['ohcanom']

key = 'HadCRUT5-0-2-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'HadCRUT5'
source_id['source_id'][key]['source_label'] = 'HadCRUT5'
source_id['source_id'][key]['release_year'] = '2025'
source_id['source_id'][key]['source_description'] = 'HadCRUT5 blended air temperature and sea surface temperature anomalies'
source_id['source_id'][key]['source_version_number'] = '5.0.2.0'
source_id['source_id'][key]['institution_id'] = 'CRU-UEA' 
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['tas','tos']

key = 'HadISDH-land-4-6-1-2024f'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_label'] = 'HadISDH'
source_id['source_id'][key]['source_name'] = 'HadISDH.land.4.6.1.2024f'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'HadISDH land near-surface humidity anomalies'
source_id['source_id'][key]['source_version_number'] = '4.6.1.2024f'
source_id['source_id'][key]['institution_id'] = 'MOHC'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['huss','hussanom','hurs','hursanom']

key = 'BSVertOzone-v1-0' 
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'BSVertOzone'
source_id['source_id'][key]['source_label'] = 'BSVertOzone'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_description'] = 'Mole concentration of ozone in air'
source_id['source_id'][key]['source_version_number'] = 'v1-0'
source_id['source_id'][key]['institution_id'] = 'DLR-BIRA'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['o3zm']

key = 'SAGE-CCI-OMPS-v0008'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'SAGE CCI OMPS'
source_id['source_id'][key]['source_label'] = 'SAGE CCI OMPS'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_description'] = 'Mole concentration of ozone in air'
source_id['source_id'][key]['source_version_number'] = 'v0008'
source_id['source_id'][key]['institution_id'] = 'FMI'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['o3']

key = 'ESA-CCI-SST-v3-0-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ESA CCI SST'
source_id['source_id'][key]['source_label'] = 'ESA CCI SST'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Sea Surface Temperature (SST) from the ESA SST CCI Climate Data Record version 3.0'
source_id['source_id'][key]['source_version_number'] = '3.0.1'
source_id['source_id'][key]['institution_id'] = 'UReading'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['tos']

key = 'HOFFMAN-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'HOFFMAN'
source_id['source_id'][key]['source_label'] = 'HOFFMAN'
source_id['source_id'][key]['release_year'] = '2014'
source_id['source_id'][key]['source_description'] = 'Carbon Mass Flux Out Of Atmosphere Due To Net Biospheric Production On Land, Surface Downward Mass Flux of Carbon As CO2'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'UCI-ORNL'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['source_variables'] = ['nbp','fgc02']

key = 'NCSCD-2-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'NCSCD'
source_id['source_id'][key]['source_label'] = 'NCSCD'
source_id['source_id'][key]['release_year'] = '2013'
source_id['source_id'][key]['source_description'] = 'Northern Circumpolar Soil Carbon Database'
source_id['source_id'][key]['source_version_number'] = '2.2'
source_id['source_id'][key]['institution_id'] = 'BCCR'
source_id['source_id'][key]['region'] = ['north_polar']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['cSoil']

key = 'OLC-ORS-V0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'OLC-ORS'
source_id['source_id'][key]['source_label'] = 'OLC-ORS'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Optimal Linear Combination of Offline land surface models, Reanalysis, and Satellite soil moisture data constrained by in situ observations'
source_id['source_id'][key]['source_version_number'] = 'V0'
source_id['source_id'][key]['institution_id'] = 'ORNL'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['source_variables'] = ['mrso']

key = 'ESACCI-CLOUD-AVHRR-AMPM-3-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_label'] = 'ESACCI-CLOUD-AVHRR-AMPM'
source_id['source_id'][key]['source_name'] = 'ESACCI-CLOUD-AVHRR-AMPM'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_description'] = 'Cloud properties derived from AVHRR (aboard NOAA and MetOp AM+PM) measurements. This dataset belongs to the ESA Cloud_cci suite of long-term coherent cloud property datasets'
source_id['source_id'][key]['source_version_number'] = '3.0'
source_id['source_id'][key]['institution_id'] = 'DWD'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['clivi', 'clt', 'clt_stderr', 'clwvi', 'lwp', 'rlus', 'rlut', 'rlutcs', 'rsdt', 'rsus', 'rsuscs', 'rsut', 'rsutcs']

key = 'CALIPSO-ICECLOUD-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_label'] = 'CALIPSO-ICECLOUD'
source_id['source_id'][key]['source_name'] = 'CALIPSO-ICECLOUD'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_description'] = 'Cloud-Aerosol Lidar and Infrared Pathfinder Satellite Observation (CALIPSO) Ice cloud'
source_id['source_id'][key]['source_version_number'] = '1.00'
source_id['source_id'][key]['institution_id'] = 'NASA-LaRC'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['cli']

key = 'RAPID-v2023-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_label'] = 'RAPID'
source_id['source_id'][key]['source_name'] = 'RAPID'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Atlantic Meridional Overturning Transport -In-situ'
source_id['source_id'][key]['source_version_number'] = 'v2023.1'
source_id['source_id'][key]['institution_id'] = 'NERC-NSF-NOAA'
source_id['source_id'][key]['region'] = ['atlantic_ocean']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['amoc']

key = 'CCI-CryoClim-FSC-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'CCI/CryoClim FSC'
source_id['source_id'][key]['source_label'] = 'CCI/CryoClim FSC'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_description'] = 'Fractional Snow Cover CDR v1 from ESA CCI / CryoClim'
source_id['source_id'][key]['source_version_number'] = '1'
source_id['source_id'][key]['institution_id'] = 'NR'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ["snc"]

key = 'HadCRUT5-0-2-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'HadCRUT5'
source_id['source_id'][key]['source_label'] = 'HadCRUT5'
source_id['source_id'][key]['release_year'] = '2025'
source_id['source_id'][key]['source_description'] = 'HadCRUT5 blended air temperature and sea surface temperature anomalies'
source_id['source_id'][key]['source_version_number'] = '5.0.2.0'
source_id['source_id'][key]['institution_id'] = 'CRU-UEA' 
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['tas','tos']

key = 'IAP-1-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'IAP'
source_id['source_id'][key]['source_label'] = 'IAP'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Sea Water Potential Temperature-In-situ (gridded) Chinese Academy of Sciences'
source_id['source_id'][key]['source_version_number'] = '4.2'
source_id['source_id'][key]['institution_id'] = 'CAS'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['thetao']

key = 'IAP-1-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'IAP'
source_id['source_id'][key]['source_label'] = 'IAP'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'Sea Water Potential Temperature-In-situ (gridded) Chinese Academy of Sciences'
source_id['source_id'][key]['source_version_number'] = '4.2'
source_id['source_id'][key]['institution_id'] = 'CAS'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['thetao']

key = 'SGP--ARMBE-atm-c1-1-8'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ARMBE'
source_id['source_id'][key]['source_label'] = 'ARMBE'
source_id['source_id'][key]['source_description'] = 'DOE ARM Best Estimate Data Products for Atmosphere and Cloud properties'
source_id['source_id'][key]['source_version_number'] = 'atm-c1-1-8'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['institution_id'] = 'DOE-ARM'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'insitu'
source_id['source_id'][key]['source_variables'] = ['uas','vas','ps','pr','hfss','hfls','tas','hfss','hfls','ta','ua','va','hur','wap']

key = 'ARMBE-atm-c1-1-8'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ARMBE'
source_id['source_id'][key]['source_label'] = 'ARMBE'
source_id['source_id'][key]['source_description'] = 'DOE ARM Best Estimate Data Products for Atmosphere and Cloud properties'
source_id['source_id'][key]['source_version_number'] = 'atm-c1-1-8'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['institution_id'] = 'DOE-ARM'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'insitu'
source_id['source_id'][key]['source_variables'] = ['uas','vas','ps','pr','hfss','hfls','tas','hfss','hfls','ta','ua','va','hur','wap']

key = 'ARMBE-cldrad-c1-1-8'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'ARMBE'
source_id['source_id'][key]['source_label'] = 'ARMBE'
source_id['source_id'][key]['source_description'] = 'DOE ARM Best Estimate Data Products for Atmosphere and Cloud properties'
source_id['source_id'][key]['source_version_number'] = 'cldrad-c1-1-8'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['institution_id'] = 'DOE-ARM'
source_id['source_id'][key]['region'] = 'north_america'
source_id['source_id'][key]['source_type'] = 'insitu'
source_id['source_id'][key]['source_variables'] = ['cl','clt','rsds','rsus','rlds','rlus','prw','clwvi','clivi','rlut','rsdt','rsut','rsdt','rsdscs']

key = 'LAI4g-1-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'LAI4g'
source_id['source_id'][key]['source_label'] = 'LAI4g'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_description'] = 'The Fourth Generation Global Inventory Modeling and Mapping Studies Leaf Area Index'
source_id['source_id'][key]['source_version_number'] = '1.2'
source_id['source_id'][key]['institution_id'] = 'PKU'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['lai']

key = 'GLODAP-2-2016b'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'GLODAP'
source_id['source_id'][key]['source_label'] = 'GLODAP'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_description'] = 'Global Ocean Data Analysis Project Version 2'
source_id['source_id'][key]['source_version_number'] = '2.2016b'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['so', 'thetao']

key = 'WECANN-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'WECANN'
source_id['source_id'][key]['source_label'] = 'WECANN'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_description'] = 'Water, Energy, and Carbon with Artificial Neural Networks'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'ColumbiaU'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['gpp', 'hfls', 'hfss']

key = 'DAI-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'DAI'
source_id['source_id'][key]['source_label'] = 'DAI'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_description'] = 'Dai and Trenberth Global River Flow and Continental Discharge Dataset'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'UCAR/NCAR - RDA'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['mrro']

key = 'LORA-1-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'LORA'
source_id['source_id'][key]['source_label'] = 'LORA'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_description'] = 'Linear Optimal Runoff Aggregate'
source_id['source_id'][key]['source_version_number'] = '1.1'
source_id['source_id'][key]['institution_id'] = 'ARCCSS'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['mrro']

key = 'HWSD-2-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'HWSD'
source_id['source_id'][key]['source_label'] = 'HWSD'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_description'] = 'Harmonized World Soil Database version 2'
source_id['source_id'][key]['source_version_number'] = '2.0'
source_id['source_id'][key]['institution_id'] = 'FAO'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['cSoil']

key = 'FLUXNET2015-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'FLUXNET2015'
source_id['source_id'][key]['source_label'] = 'FLUXNET2015'
source_id['source_id'][key]['release_year'] = '2020'
source_id['source_id'][key]['source_description'] = 'FLUXNET Community Product'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'FLUXNET'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['gpp']

key = 'PRISM-M3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'PRISM'
source_id['source_id'][key]['source_label'] = 'PRISM'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_description'] = 'PRISM Spatial Climate Datasets for CONUS'
source_id['source_id'][key]['source_version_number'] = 'M3'
source_id['source_id'][key]['institution_id'] = 'OSU'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','tas']

key = 'OSISAF-V3'  
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'OSISAF/CCI SIC'
source_id['source_id'][key]['source_label'] = 'OSISAF/CCI SIC'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_description'] = 'Sea Ice Concentration (SIC) CDR v3 from EUMETSAT OSI SAF / ESA CCI'
source_id['source_id'][key]['source_version_number'] = '3'
source_id['source_id'][key]['institution_id'] = 'MET-Norway'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ["siconc"]

key = 'FireCCI-v5-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'FireCCI'
source_id['source_id'][key]['source_label'] = 'FireCCI'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'MODIS FireCCI Burned Area product'
source_id['source_id'][key]['source_version_number'] = '5.1'
source_id['source_id'][key]['institution_id'] = 'UAH'
source_id['source_id'][key]['region'] = ['global_land']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['burntFractionAll']

key = 'WOA2023'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'WOA'
source_id['source_id'][key]['source_label'] = 'WOA'
source_id['source_id'][key]['release_year'] = '2024'
source_id['source_id'][key]['source_description'] = 'World Ocean Atlas'
source_id['source_id'][key]['source_version_number'] = '2023'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['so','thetao']

key = 'livneh-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'livneh'
source_id['source_id'][key]['source_label'] = 'livneh'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS near-surface gridded meteorological and derived hydrometeorological data data provided by the NOAA PSL'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-ESRL-PSD'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','sfcWind']

key = 'livneh-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'livneh'
source_id['source_id'][key]['source_label'] = 'livneh'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS near-surface gridded meteorological and derived hydrometeorological data data provided by the NOAA PSL'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-ESRL-PSD'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','sfcWind']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'livneh-unsplit-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'livneh_unsplit' 
source_id['source_id'][key]['source_label'] = 'livneh_unsplit'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS unsplit'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'UCSD-SIO'
source_id['source_id'][key]['region'] = ['north_america']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr','tasmin', 'tasmax','sfcWind'] 

key = 'GERB-HR-ED01-1-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'GERB'
source_id['source_id'][key]['source_label'] = 'GERB'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_description'] = 'Geostationary Earth Radiation Budget'
source_id['source_id'][key]['institution_id'] = 'ImperialCollege'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['source_variables'] = ['rlut','rsut']
source_id['source_id'][key]['source_version_number'] = 'HR_ED01_1.1'

key = 'MSWEP-V280-Past'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MSWEP'
source_id['source_id'][key]['source_label'] = 'MSWEP'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Multi-Source Weighted-Ensemble Precipitation'
source_id['source_id'][key]['institution_id'] = 'GloH2O'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V280-Past'

key = 'MSWEP-V280-Past-nogauge'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MSWEP'
source_id['source_id'][key]['source_label'] = 'MSWEP'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Multi-Source Weighted-Ensemble Precipitation'
source_id['source_id'][key]['institution_id'] = 'GloH2O'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V280-Past-nogauge'

key = 'MSWEP-V280-NRT'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MSWEP'
source_id['source_id'][key]['source_label'] = 'MSWEP'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_description'] = 'Multi-Source Weighted-Ensemble Precipitation'
source_id['source_id'][key]['institution_id'] = 'GloH2O'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V280-Past-NRT'

key = 'MUR25-4-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'MUR25'
source_id['source_id'][key]['source_label'] = 'MUR25'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_description'] = 'Multiscale Ultrahigh Resolution L4 Sea-Surface Temperature'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['source_variables'] = ['tos']
source_id['source_id'][key]['source_version_number'] = 'v4.2'

key = 'IMERG-V06-EU'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Livneh daily CONUS near-surface gridded meteorological and derived hydrometeorological data'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-EU'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-EU'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-EU'

key = 'IMERG-V06-FC'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-FC'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-FC'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-FC'

key = 'IMERG-V06B-Final-3hr'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG averaged to 3-hourly maps'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-Final-3hr'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-Final-3hr'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06B'

key = 'IMERG-V07-Final'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG 30-min, 0.1x0.1 degrees'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V07-Final'
source_id['source_id'][key]['source_name'] = 'IMERG-V07-Final'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V07'

key = 'IMERG-V06-FU'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-FU'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-FU'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-FU'

key = 'IMERG-V06-LU'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA IMERG prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'IMERG-V06-LU'
source_id['source_id'][key]['source_name'] = 'IMERG-V06-LU'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V06-LU'

key = 'nClimGrid-Monthly-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'nClimGrid-Monthly-1-0'
source_id['source_id'][key]['release_year'] = '2014'
source_id['source_id'][key]['source_description'] = 'NOAA nClimGrid-Monthly'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = 'north_america'
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'nClimGrid-Monthly-1-0'
source_id['source_id'][key]['source_variables'] = ['pr','tas','tasmax','tasmin']

key = 'nClimGrid-Daily-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'nClimGrid-Daily-1-0'
source_id['source_id'][key]['release_year'] = '2014'
source_id['source_id'][key]['source_description'] = 'NOAA nClimGrid-Daily'
source_id['source_id'][key]['source_version_number'] = '1.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = 'north_america'
source_id['source_id'][key]['source_type'] = 'gridded_insitu'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'nClimGrid-Daily-1-0'
source_id['source_id'][key]['source_variables'] = ['pr','tas','tasmax','tasmin']

key = 'OISST-L4-AVHRR-only-v2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'SST-AVHRR_only.v2 2008 NOAA 1/4 Degree Daily Optimum Interpolation Sea Surface Temperature Analysis using AVHRR, Version 2'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'OISST_L4_AVHRR-only-v2'
source_id['source_id'][key]['source_name'] = 'OISST_L4_AVHRR-only-v2'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_variables'] = ['ts']
source_id['source_id'][key]['source_version_number'] = 'v2'

key = 'HadISST-1-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'HadISST 1.1 monthly average sea surface temperature'
source_id['source_id'][key]['institution_id'] = 'MOHC'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'HadISST-1-1'
source_id['source_id'][key]['source_name'] = 'HadISST-1-1'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_variables'] = ['ts']
source_id['source_id'][key]['source_version_number'] = '1-1'

key = 'AVISO-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Gridded sea surface heights above geoid'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'AVISO-1-0'
source_id['source_id'][key]['source_name'] = 'AVISO-1-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['zos']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'TropFlux-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'TropFlux - Air-Sea Fluxes for the Global Tropical Oceans'
source_id['source_id'][key]['institution_id'] = 'INCOIS-NIO-IPSL'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TropFlux-1-0'
source_id['source_id'][key]['source_name'] = 'TropFlux-1-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global_ocean']
source_id['source_id'][key]['source_variables'] = ['tas','ts','hfls','hfss','hfns','tauu','tauv']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'AVISO-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Gridded sea surface heights above geoid'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'AVISO-1-0'
source_id['source_id'][key]['source_name'] = 'AVISO-1-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['zos']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'CERES-EBAF-4-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages'
source_id['source_id'][key]['institution_id'] = 'NASA-LaRC'
source_id['source_id'][key]['release_year'] = '2018'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CERES-EBAF-4-0'
source_id['source_id'][key]['source_name'] = 'CERES-EBAF4-0'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['rlut','rsut','rsutcs','rlutcs']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'CERES-EBAF-4-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages'
source_id['source_id'][key]['institution_id'] = 'NASA-LaRC'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CERES-EBAF-4-1'
source_id['source_id'][key]['source_name'] = 'CERES-EBAF4-1'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['rlut','rsut','rsutcs','rlutcs']
source_id['source_id'][key]['source_version_number'] = '4.1'

key = 'CERES-EBAF-4-2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages'
source_id['source_id'][key]['institution_id'] = 'NASA-LaRC'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CERES-EBAF-4-2'
source_id['source_id'][key]['source_name'] = 'CERES-EBAF4-2'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['rlut','rsut','rsutcs','rlutcs']
source_id['source_id'][key]['source_version_number'] = '4.2'

key = 'ERA-40'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF - ERA-40 (European ReAnalysis 1957-2002)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2005'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERA-40'
source_id['source_id'][key]['source_name'] = 'ECMWF ERA-40'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'ERA-5'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ERA5 (European ReAnalysis)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2019'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERA-5'
source_id['source_id'][key]['source_name'] = 'ECMWF ERA-5'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tas','psl','zg','ta','ua','va','pr']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'CMAP-V1902'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CMAP Precipitation'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CMAP'
source_id['source_id'][key]['source_name'] = 'CMAP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'V1902'

key = 'CMORPH-1-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'CMORPH'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CMORPH'
source_id['source_id'][key]['source_name'] = 'CMORPH'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'CMORPH-1-0-CRT'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NOAA CMORPH prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CMORPH'
source_id['source_id'][key]['source_name'] = 'CMORPH'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'GPCP-Daily-3-2'
source_id['source_id'][key] = {}
# source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
# source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3.2'

key = 'GPCP-Monthly-3-2'
source_id['source_id'][key] = {}
# source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
# source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3.2'

key = 'GPCP-2-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '2.3'

key = 'GPCP-1-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Merged Precipitation'
source_id['source_id'][key]['institution_id'] = 'NASA-JPL'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.3'

key = 'GPCP-1DD-CDR-v1-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Daily GPCP CDR prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.3'

key = 'GPCP-IP'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA GPCP prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = 'N/A'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GPCP'
source_id['source_id'][key]['source_name'] = 'GPCP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '1.3'

key = 'GSMAP-gauges-NRT-v6-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'JAXA GSMAP prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'JAXA'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'GSMAP'
source_id['source_id'][key]['source_name'] = 'GSMAP'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '6.0'

key = 'ERA-INT'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF-ERAINT 1.0 (2010): ECMWF - ERAINT (European ReAnalysis 1989-2010)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2010'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERAINT'
source_id['source_id'][key]['source_name'] = 'ECMWF-ERAINT'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va','zg']
source_id['source_id'][key]['source_version_number'] = 'N/A'

key = 'JRA25'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'JRA25 1.0 (2002): JRA25 (Japanese ReAnalysis 1957-2002)'
source_id['source_id'][key]['institution_id'] = 'MRI'
source_id['source_id'][key]['release_year'] = '2002'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'MRI-JRA25'
source_id['source_id'][key]['source_name'] = 'MRI-JRA25'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ta','ua','va','zg']
source_id['source_id'][key]['source_version_number'] = 'N/A'

key = '20CR-V2'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Monthly NOAA-CIRES 20th Century Reanalysis V2'
source_id['source_id'][key]['institution_id'] = 'NOAA-ESRL-PSD'
source_id['source_id'][key]['release_year'] = '2006'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = '20CR'
source_id['source_id'][key]['source_name'] = '20CR'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ts','psl']
source_id['source_id'][key]['source_version_number'] = 'V2'

key = 'ERA-20C'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'ECMWF - ERA-20C (European ReAnalysis 1900-2010)'
source_id['source_id'][key]['institution_id'] = 'ECMWF'
source_id['source_id'][key]['release_year'] = '2014'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'ECMWF-ERA-20C'
source_id['source_id'][key]['source_name'] = 'ECMWF ERA-20C'
source_id['source_id'][key]['source_type'] = 'reanalysis'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['ts','psl']
source_id['source_id'][key]['source_version_number'] = '1.0'

key = 'TRMM-3B42v-7'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA-TRMM prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TRMM'
source_id['source_id'][key]['source_name'] = 'TRMM'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3B42v.7'

key = 'TRMM-3B42-IR-v7-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA-TRMM prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TRMM'
source_id['source_id'][key]['source_name'] = 'TRMM'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3B42.IR.v7.0'

key = 'TRMM-3B42-MW-v7-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NASA-TRMM prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NASA-GSFC'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'TRMM'
source_id['source_id'][key]['source_name'] = 'TRMM'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = '3B42.MW.v7.0'

key = 'CCMP-3-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Cross-Calibrated Multiplatform v3.1 (2023): 10m Surface Wind'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'CCMP-3-1'
source_id['source_id'][key]['source_name'] = 'CCMP-3-1'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['sfcWind']
source_id['source_id'][key]['source_version_number'] = '3.1'

key = 'RSS-MSU-TLS-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MSU Temperature Lower Stratosphere v4.0'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MSU-TLS'
source_id['source_id'][key]['source_name'] = 'RSS-MSU-TLS'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tls']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'RSS-MSU-TLT-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MSU Temperature Lower Troposphere v4.0'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MSU-TLT'
source_id['source_id'][key]['source_name'] = 'RSS-MSU-TLT'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tlt']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'RSS-MSU-TMT-4'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MSU Temperature Middle Troposphere v4.0'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2016'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MSU-TMT'
source_id['source_id'][key]['source_name'] = 'RSS-MSU-TMT'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tmt']
source_id['source_id'][key]['source_version_number'] = '4.0'

key = 'RSS-MWIR-SST-5-1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS MWIR v5.1 Foundation OISST'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-MWIR-SST'
source_id['source_id'][key]['source_name'] = 'RSS-MWIR-SST'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['tos']
source_id['source_id'][key]['source_version_number'] = '5.1'

key = 'RSS-PRW-6-6-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-PRW 6.6.0 (2017): Water Vapor Path'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-PRW'
source_id['source_id'][key]['source_name'] = 'RSS-PRW'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['prw']
source_id['source_id'][key]['source_version_number'] = '6.6.0'

key = 'RSS-PRW-v07r01'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-PRW 7.0 (2019): Water Vapor Path'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2017'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-PRW'
source_id['source_id'][key]['source_name'] = 'RSS-PRW'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['prw']
source_id['source_id'][key]['source_version_number'] = '7.1'

key = 'RSS-PRW-v07r02'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-PRW 7.2 (2022): Water Vapor Path'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2022'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-PRW'
source_id['source_id'][key]['source_name'] = 'RSS-PRW'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['prw']
source_id['source_id'][key]['source_version_number'] = '7.2'

key = 'RSS-SMAP-SSS-v05r01'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Satellite derived SSS produced by RSS'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-SMAP-SSS'
source_id['source_id'][key]['source_name'] = 'RSS-SMAP-SSS'
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['region'] = ['global ocean']
source_id['source_id'][key]['source_variables'] = ['sos']
source_id['source_id'][key]['source_version_number'] = '5.0'

key = 'RSS-SMAP-SSS-Monthly-5-3'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'Satellite derived SSS produced by RSS'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-SMAP-SSS-Monthly-5-3'
source_id['source_id'][key]['source_name'] = 'RSS-SMAP-SSS-Monthly-5-3'
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['region'] = ['global ocean']
source_id['source_id'][key]['source_variables'] = ['sos']
source_id['source_id'][key]['source_version_number'] = '5.3'

key = 'RSS-sfcWind-v07r01'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'RSS-sfcWind 7.0 (2021): 10m Surface Wind'
source_id['source_id'][key]['institution_id'] = 'RSS'
source_id['source_id'][key]['release_year'] = '2021'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'RSS-sfcWind'
source_id['source_id'][key]['source_name'] = 'RSS-sfcWind'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['sfcWind']
source_id['source_id'][key]['source_version_number'] = '7.1'

key = 'PERSIANN-CDRv1r1'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_description'] = 'NOAA PERSIANN prepared for FROGS'
source_id['source_id'][key]['institution_id'] = 'NOAA'
source_id['source_id'][key]['release_year'] = '2015'
source_id['source_id'][key]['source_id'] = key
source_id['source_id'][key]['source_label'] = 'PERSIANN'
source_id['source_id'][key]['source_name'] = 'PERSIANN'
source_id['source_id'][key]['source_type'] = 'satellite_blended'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_variables'] = ['pr']
source_id['source_id'][key]['source_version_number'] = 'CDRv1r1'

key = 'C3S-GTO-ECV-9-0'
source_id['source_id'][key] = {}
source_id['source_id'][key]['source_name'] = 'C3S-GTO-ECV'
source_id['source_id'][key]['source_label'] = 'C3S-GTO-ECV'
source_id['source_id'][key]['release_year'] = '2023'
source_id['source_id'][key]['source_description'] = 'GOME-type Total Ozone Essential Climate Variable (GTO-ECV), generated by combining measurements from several nadir-viewing satellite sensors (GOME/ERS-2, SCIAMACHY/Envisat, OMI/Aura, GOME-2/MetOp-A, GOME-2/MetOp-B, GOME-2/MetOp-C, and TROPOMI/Sentinel-5p'
source_id['source_id'][key]['source_version_number'] = '9.0'
source_id['source_id'][key]['institution_id'] = 'DLR-BIRA'
source_id['source_id'][key]['region'] = ['global']
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
source_id['source_id'][key]['source_variables'] = ['o3']
source_id['source_id'][key]['source_id'] = key

